import type { Metadata } from "next";
import {
  roboto,
  inter,
  openSans,
  shadowsIntoLight,
  raleway,
  montserrat,
  barrio,
  delius,
  audiowide,
  merriweather
} from "@/constants/fonts";
import "./globals.scss";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "LinkCard",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} ${openSans.variable} ${shadowsIntoLight.variable} ${raleway.variable} ${montserrat.variable} ${barrio.variable} ${delius.variable} ${audiowide.variable} ${merriweather.variable}`}
      >
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#181818",
              color: "#f3f4f6",
              border: "1px solid #2c2c2c"
            }
          }}
        />
      </body>
    </html>
  );
}
