import type { Metadata } from "next";
import {
  roboto,
  inter,
  openSans,
  shadowsIntoLight,
  raleway,
  montserrat,
  barrio,
  delius,
  audiowide,
  merriweather
} from "@/constants/fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: "LinkCard",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} ${openSans.variable} ${shadowsIntoLight.variable} ${raleway.variable} ${montserrat.variable} ${barrio.variable} ${delius.variable} ${audiowide.variable} ${merriweather.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
