@apiURL = http://localhost:5000/api
@resetToken = e3a1d2a2ebc2c4766a26242cf8e3b49fbe52228605b190f8c447e9ec18e86c73
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGU1M2Y2NzQ5M2U0NTczZDEwN2UxZjYiLCJ1c2VybmFtZSI6Im5payIsImlhdCI6MTc2MDAwMTE3NCwiZXhwIjoxNzYwNjA1OTc0fQ.GM88WEp92ezVBRbKwYSqTZMW9CkSsPlrc7QpMW5_M5A

### HealthCheck
GET {{apiURL}}/healthcheck

### Реєстрація
POST {{apiURL}}/register
Content-Type: application/json

{
    "username": "NikitaBerezhnyj",
    "email": "nikita.berezhnyj@gmail.com",
    "password": "Nik_0402"
}

### Авторизація
POST {{apiURL}}/login
Content-Type: application/json

{
    "email": "kitnikita06@gmail.com",
    "password": "Nik_0402"
}

### Надсилання листа, якщо забули пароль
POST {{apiURL}}/password/forgot
Content-Type: application/json

{
  "email": "kitnikita06@gmail.com"
}

### Зміна пароля
POST {{apiURL}}/password/reset/{{resetToken}}
Content-Type: application/json

{
    "email": "kitnikita06@gmail.com",
    "password": "Nik_0402"
}

### Отримання інформації про користувача
GET {{apiURL}}/user/nik

### Оновлення BIO
PATCH {{apiURL}}/user/nik
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "bio": "Name is nik..."
}

### Оновлення одного елемента у links
PATCH {{apiURL}}/user/nik
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "links": [
    { "title": "Email", "url": "kitnikita06@gmail.com"},
    { "title": "GitHub Profile", "url": "https://github.com/NikitaBerezhnyj" }
  ]
}

### Оновлення стилів
PATCH {{apiURL}}/user/nik
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "styles": {
    "fontSize": "20px",
    "background": {
      "value": {
        "color": "#123456",
        "gradient": { "start": "#abcdef", "end": "#fedcba", "angle": "45deg" }
      }
    }
  }
}

### Видалення користувача
DELETE {{apiURL}}/user/NikName
Authorization: Bearer {{jwtToken}}