@apiURL = http://localhost:5000/api
@resetToken = e3a1d2a2ebc2c4766a26242cf8e3b49fbe52228605b190f8c447e9ec18e86c73
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGU5MzZmOTc3YWU2NjU5NzY4MWM1ZGMiLCJpYXQiOjE3NjA0NzE3OTEsImV4cCI6MTc2MTA3NjU5MX0.BwB_iFeJwb6I6x1MpxjRpYJTlXHvkaSkV-LBeNNSTHo

### HealthCheck
GET {{apiURL}}/healthcheck


### Реєстрація користувача
POST {{apiURL}}/register
Content-Type: application/json

{
    "username": "TestUser123",
    "email": "test.user@example.com",
    "password": "TestPass123!"
}


### Авторизація користувача
POST {{apiURL}}/login
Content-Type: application/json

{
    "email": "test.user@example.com",
    "password": "TestPass123!"
}


### Надсилання листа для відновлення пароля
POST {{apiURL}}/password/forgot
Content-Type: application/json

{
  "email": "test.user@example.com"
}


### Зміна пароля
POST {{apiURL}}/password/reset/{{resetToken}}
Content-Type: application/json

{
    "email": "test.user@example.com",
    "password": "NewSecurePass123!"
}


### Отримання інформації про користувача
GET {{apiURL}}/user/TestUser123


### Оновлення BIO користувача
PATCH {{apiURL}}/user/TestUser123
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "bio": "Hello! I'm a demo user for API testing."
}


### Оновлення одного елемента у links
PATCH {{apiURL}}/user/TestUser123
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "links": [
    { "title": "Email", "url": "test.user@example.com" },
    { "title": "GitHub Profile", "url": "https://github.com/demo-user" }
  ]
}


### Оновлення стилів користувача
PATCH {{apiURL}}/user/TestUser123
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "styles": {
    "fontSize": "20px",
    "background": {
      "value": {
        "color": "#123456",
        "gradient": { "start": "#abcdef", "end": "#fedcba", "angle": "45deg" }
      }
    }
  }
}


### Оновлення username та email
PATCH {{apiURL}}/user/TestUser123
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "username": "UpdatedUser",
  "email": "updated.user@example.com"
}


### Видалення користувача
DELETE {{apiURL}}/user/UpdatedUser
Authorization: Bearer {{jwtToken}}
