@apiUrl = http://localhost:8080

@testUsername = TestUser123
@testEmail = test.user@example.com
@testPassword = TestPass123!

@resetToken = Q2ZESjhOdGptdndHVW01Smw4STEyMGtBYUNtZUlKdjE3WGhua29uN1FBcFZCQzZoYVczRW5pNVRTcTc0WlVsRnVTQ0lFdkdldnRBRW1rTC9yY2M4RlJWdUozMXFsbFNDMWVmOWpLam01V29QRzdmYTZuaFExcnRKbXk2andkUitTbDVHZjRHaW5raEplcVExZERhWmVQaEFaR1EraEROcjkrdVBtanR6TWZTK3RSM3FqVWZFd3FNRDh0NDhiUFQ3ZUVTakh4cGY2WFNMbEhyaHlIdEJ5OFlsK2FoUnF6TVFtRWNBeDhoNlhvMHp2QXhs

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxYTA2MTRjLTUzYTgtNzJmMS05OTNhLTA0ZGE1OTAwMDM3NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0VXNlcjEyMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3QudXNlckBleGFtcGxlLmNvbSIsImV4cCI6MTc4OTA1Mjg4MywiaXNzIjoiTGlua0NhcmQiLCJhdWQiOiJMaW5rQ2FyZCJ9.xfJLLAkOcZb7Az3FdQrFZJTbpV5bA6mFMDReE4WJVKs
@refreshToken = Pi5bM6JQWwiOrEO90NDBnxrrcVPg+gm8kM/IzFLmOcwmYBzwBl9DYqvZwCVG1rrMYwxpt+DwY60/S/jEZLqLng==

### Health Check
GET {{apiUrl}}/healthcheck

### Register
POST {{apiUrl}}/auth/register
Content-Type: application/json

{
  "username": "{{testUsername}}",
  "email": "{{testEmail}}",
  "password": "{{testPassword}}"
}

### Login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{testEmail}}",
  "password": "{{testPassword}}"
}

### Send password reset email
POST {{apiUrl}}/auth/password/forgot
Content-Type: application/json

{
  "email": "{{testEmail}}"
}

### Reset password
POST {{apiUrl}}/auth/password/reset/{{resetToken}}
Content-Type: application/json

{
  "email": "{{testEmail}}",
  "newPassword": "{{testPassword}}"
}

### Refresh token
POST {{apiUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout
POST {{apiUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Get user by username
GET {{apiUrl}}/users/{{testUsername}}

### Update username & email
PATCH {{apiUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "{{testEmail}}",
  "email": "{{testPassword}}"
}

### Update bio
PATCH {{apiUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "bio": "Hello! I'm a demo user for API testing."
}

### Update links
PATCH {{apiUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "links": [
    {
      "title": "Email",
      "url": "mailto:test.user@example.com"
    },
    {
      "title": "GitHub Profile",
      "url": "https://github.com/demo-user"
    },
    {
      "title": "My Blog",
      "url": "https://myblog.example.com"
    }
  ]
}

### Update styles
PATCH {{apiUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "styles": {
    "typography": {
      "fontSize": "16px",
      "textAlign": "center"
    },
    "background": {
      "repeat": "no-repeat"
    }
  }
}

### Upload avatar
PUT {{apiUrl}}/users/me/avatar
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="avatar.jpg"
Content-Type: image/jpeg

< ../client/public/images/avatar.jpg
--boundary--

### Upload background
PUT {{apiUrl}}/users/me/background
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="background.jpg"
Content-Type: image/jpeg

< ../client/public/images/avatar.jpg
--boundary--

### Delete current user
DELETE {{apiUrl}}/users/me
Authorization: Bearer {{accessToken}}