// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkCard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908193954_AddDataProtectionKeys")]
    partial class AddDataProtectionKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkCard.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LinkCard.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LinkCard.Entities.UserLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Order");

                    b.ToTable("UserLinks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LinkCard.Entities.ApplicationUser", b =>
                {
                    b.OwnsOne("LinkCard.Entities.UserStyles", "Styles", b1 =>
                        {
                            b1.Property<Guid>("ApplicationUserId");

                            b1.HasKey("ApplicationUserId");

                            b1.ToTable("AspNetUsers");

                            b1
                                .ToJson("Styles")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");

                            b1.OwnsOne("LinkCard.Entities.BackgroundStyle", "Background", b2 =>
                                {
                                    b2.Property<Guid>("UserStylesApplicationUserId");

                                    b2.Property<int>("Type");

                                    b2.HasKey("UserStylesApplicationUserId");

                                    b2.ToTable("AspNetUsers");

                                    b2.WithOwner()
                                        .HasForeignKey("UserStylesApplicationUserId");

                                    b2.OwnsOne("LinkCard.Entities.BackgroundValue", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("BackgroundStyleUserStylesApplicationUserId");

                                            b3.Property<string>("Color")
                                                .IsRequired();

                                            b3.Property<string>("ImageKey")
                                                .IsRequired();

                                            b3.Property<string>("Position")
                                                .IsRequired();

                                            b3.Property<string>("Repeat")
                                                .IsRequired();

                                            b3.Property<string>("Size")
                                                .IsRequired();

                                            b3.HasKey("BackgroundStyleUserStylesApplicationUserId");

                                            b3.ToTable("AspNetUsers");

                                            b3.WithOwner()
                                                .HasForeignKey("BackgroundStyleUserStylesApplicationUserId");

                                            b3.OwnsOne("LinkCard.Entities.GradientStyle", "Gradient", b4 =>
                                                {
                                                    b4.Property<Guid>("BackgroundValueBackgroundStyleUserStylesApplicationUserId");

                                                    b4.Property<string>("Angle")
                                                        .IsRequired();

                                                    b4.Property<string>("End")
                                                        .IsRequired();

                                                    b4.Property<string>("Start")
                                                        .IsRequired();

                                                    b4.HasKey("BackgroundValueBackgroundStyleUserStylesApplicationUserId");

                                                    b4.ToTable("AspNetUsers");

                                                    b4.WithOwner()
                                                        .HasForeignKey("BackgroundValueBackgroundStyleUserStylesApplicationUserId");
                                                });

                                            b3.Navigation("Gradient")
                                                .IsRequired();
                                        });

                                    b2.Navigation("Value")
                                        .IsRequired();
                                });

                            b1.OwnsOne("LinkCard.Entities.ColorScheme", "Colors", b2 =>
                                {
                                    b2.Property<Guid>("UserStylesApplicationUserId");

                                    b2.Property<string>("Border")
                                        .IsRequired();

                                    b2.Property<string>("ContentBackground")
                                        .IsRequired();

                                    b2.Property<string>("LinkText")
                                        .IsRequired();

                                    b2.Property<string>("Text")
                                        .IsRequired();

                                    b2.HasKey("UserStylesApplicationUserId");

                                    b2.ToTable("AspNetUsers");

                                    b2.WithOwner()
                                        .HasForeignKey("UserStylesApplicationUserId");

                                    b2.OwnsOne("LinkCard.Entities.ButtonColors", "Button", b3 =>
                                        {
                                            b3.Property<Guid>("ColorSchemeUserStylesApplicationUserId");

                                            b3.Property<string>("Background")
                                                .IsRequired();

                                            b3.Property<string>("HoverBackground")
                                                .IsRequired();

                                            b3.Property<string>("HoverText")
                                                .IsRequired();

                                            b3.Property<string>("Text")
                                                .IsRequired();

                                            b3.HasKey("ColorSchemeUserStylesApplicationUserId");

                                            b3.ToTable("AspNetUsers");

                                            b3.WithOwner()
                                                .HasForeignKey("ColorSchemeUserStylesApplicationUserId");
                                        });

                                    b2.Navigation("Button")
                                        .IsRequired();
                                });

                            b1.OwnsOne("LinkCard.Entities.Layout", "Layout", b2 =>
                                {
                                    b2.Property<Guid>("UserStylesApplicationUserId");

                                    b2.Property<string>("BorderRadius")
                                        .IsRequired();

                                    b2.Property<string>("ContentGap")
                                        .IsRequired();

                                    b2.Property<string>("ContentPadding")
                                        .IsRequired();

                                    b2.HasKey("UserStylesApplicationUserId");

                                    b2.ToTable("AspNetUsers");

                                    b2.WithOwner()
                                        .HasForeignKey("UserStylesApplicationUserId");
                                });

                            b1.OwnsOne("LinkCard.Entities.Typography", "Typography", b2 =>
                                {
                                    b2.Property<Guid>("UserStylesApplicationUserId");

                                    b2.Property<string>("Font")
                                        .IsRequired();

                                    b2.Property<string>("FontSize")
                                        .IsRequired();

                                    b2.Property<string>("FontWeight")
                                        .IsRequired();

                                    b2.Property<string>("TextAlign")
                                        .IsRequired();

                                    b2.HasKey("UserStylesApplicationUserId");

                                    b2.ToTable("AspNetUsers");

                                    b2.WithOwner()
                                        .HasForeignKey("UserStylesApplicationUserId");
                                });

                            b1.Navigation("Background")
                                .IsRequired();

                            b1.Navigation("Colors")
                                .IsRequired();

                            b1.Navigation("Layout")
                                .IsRequired();

                            b1.Navigation("Typography")
                                .IsRequired();
                        });

                    b.Navigation("Styles")
                        .IsRequired();
                });

            modelBuilder.Entity("LinkCard.Entities.RefreshToken", b =>
                {
                    b.HasOne("LinkCard.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkCard.Entities.UserLink", b =>
                {
                    b.HasOne("LinkCard.Entities.ApplicationUser", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LinkCard.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LinkCard.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkCard.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LinkCard.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkCard.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
